In [51]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report



In [37]:
data = pd.read_excel("/weather.xlsx")

In [39]:
print("Original Data:\n", data.head())
data = data.dropna(subset=['WeatherCondition'])   # remove missing target
data = data.fillna(data.mean(numeric_only=True))   # fill numeric missing values
data = data.drop(columns=['Date'])                 # drop unnecessary column

print("\nCleaned Data:\n", data.head())

Original Data:
         Date  Temperature  Humidity  WindSpeed  Precipitation  Pressure  \
0 2026-01-01         25.0      60.0       10.0            2.0    1012.0   
1 2026-01-02         30.0      65.0        NaN            5.0    1015.0   
2 2026-01-03         28.0       NaN       12.0            0.0    1010.0   
3 2026-01-04          NaN      70.0       14.0            1.0       NaN   
4 2026-01-05        100.0      75.0       13.0            NaN    1020.0   

  WeatherCondition  
0            Sunny  
1           Cloudy  
2            Rainy  
3            Sunny  
4              NaN  

Cleaned Data:
    Temperature  Humidity  WindSpeed  Precipitation  Pressure WeatherCondition
0        25.00     60.00       10.0            2.0   1012.00            Sunny
1        30.00     65.00       59.0            5.0   1015.00           Cloudy
2        28.00     68.75       12.0            0.0   1010.00            Rainy
3        26.25     70.00       14.0            1.0   2009.25            Sunny
5

In [40]:
le = LabelEncoder()
data['WeatherCondition'] = le.fit_transform(data['WeatherCondition'])

In [41]:
X = data.drop('WeatherCondition', axis=1)
y = data['WeatherCondition']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [43]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
dt = DecisionTreeClassifier()
knn = KNeighborsClassifier(n_neighbors=3)
svm = SVC(kernel='linear')

dt.fit(X_train, y_train)
knn.fit(X_train, y_train)
svm.fit(X_train, y_train)

SVC(kernel='linear')

In [45]:
dt_pred = dt.predict(X_test)
knn_pred = knn.predict(X_test)
svm_pred = svm.predict(X_test)

In [49]:
def evaluate(name, y_test, y_pred):
    print("\n")
    print(name)
    print("")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

In [52]:
evaluate("Decision Tree:", y_test, dt_pred)
evaluate("k-NN:", y_test, knn_pred)
evaluate("SVM:", y_test, svm_pred)



Decision Tree:

Accuracy: 0.0
Confusion Matrix:
 [[0 1]
 [0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



k-NN:

Accuracy: 0.0
Confusion Matrix:
 [[0 1]
 [0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



SVM:

Accuracy: 0.0
Confusion Matrix:
 [[0 1]
 [0 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_